apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vxlan-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-vxlan-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kube-vxlan-controller
    namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vxlan-controller
  namespace: kube-system
data:
  vxeth0: id=100 up
  vxeth1: id=101 up
  vxeth2: id=102 up
  vxeth3: id=103 up
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vxlan-controller-config
  namespace: kube-system
data:
  config: |
    [{'kube-vxlan-controller', [
        {db_file, "/usr/share/kube-vxlan-controller/db"},
        {selector, "vxlan.openvnf.org"},
        {annotation, "vxlan.openvnf.org/networks"}
    ]}].
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: kube-vxlan-controller
  name: kube-vxlan-controller
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        run: kube-vxlan-controller
    spec:
      containers:
      - name: epmd
        image: aialferov/epmd:20.3.2
      - name: kube-vxlan-controller
        image: openvnf/kube-vxlan-controller:0.9.3
        args:
        - run
        volumeMounts:
        - name: kube-vxlan-controller-config
          mountPath: /etc/kube-vxlan-controller
        - name: kube-vxlan-controller-db
          mountPath: /usr/share/kube-vxlan-controller
      volumes:
      - name: kube-vxlan-controller-config
        configMap:
          name: kube-vxlan-controller-config
      - name: kube-vxlan-controller-db
        emptyDir: {}
      serviceAccount: kube-vxlan-controller
      serviceAccountName: kube-vxlan-controller
